#MYSQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_ecommerce?createDatabaseIfNotExist=true
    username: root
    password: tiger
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        
 #SMTP Configuration
  mail:
    host: smtp.gmail.com
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            port: 587
