#MYSQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_ecommerce?createDatabaseIfNotExist=true
    username: root
    password: tiger
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        
 #SMTP Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username} 
    password: ${mail.password}
    properties:   
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            
application:
   jwt:
      secret: ${jwt.secret}
      access_expiry_seconds: 3600
      refresh_expiry_seconds: 1296000
   cookie:
      domain: localhost
      samesite: Lax
      secure: false
            